### ISSUE TITLE
local storage quota sometimes exceeded

### ISSUE THREAD

**Issue by ArtrenH** [ArtrenH/VPlan_FR#84]

**Comment by ArtrenH** [comment]
should be fixed with 313ce7c1511244a2a9962567cc09a36597f49204

**Comment by Belissimo-T** [comment]
This still happened to me since that commit. Cannot tell you how to repro.

**Comment by ArtrenH** [comment]
Could reproduce by switching between 3 schools and loading plans until it is no longer possible
Please move this issue to #95 to solve the problem
